### ISSUE TITLE
[FEATURE] ID column in the table 

### ISSUE THREAD

**Issue by yukie-a** [glygener/glygen-array-frontend#12]
(This may be discussed at the last meeting..?) 

It would be better to have the ID column (not only for the internal ID) at the Glyacn table (also other tables). 
The ID will help users to find the Glycans which entered last.

**Comment by senaarpinar** [comment]
ID's are not generated in order (they are random like glytoucan accession numbers) so I don't think it will help with finding the last entered Glycan. But I believe we are ordering the table based on creation date after adding the glycan so the newly added glycan should be the first one shown.

**Comment by ReneRanzinger** [comment]
I think Yukie is refereeing to the feature ID and feature name we recently added.

**Comment by yukie-a** [comment]
Yes, similar to the Feature ID, it will be nice to have Glycan IDs and Linker ID respecitively.  

When I started to enter the glycan structures (e.g. 100 entries), I could not finish in one go.  And, when I came back to continue data entry, it took me some time to find the glycan structure i entered last....
