### ISSUE TITLE
[BUG] Empty error message

### ISSUE THREAD

**Issue by yukie-a** [glygener/glygen-array-frontend#13]
An empty error message appeared when I created a new linker with
- Linker Type: Small Molecule
- Clasification: ceramide
- Name: Ceramide
- Comments: natural glycolipids with various ceramide moieties

I can not complete this new linker entry by clicking 'Finish' button.

![EmptyErrorMsg](https://user-images.githubusercontent.com/67378697/123293344-cfa53780-d50b-11eb-9f2b-c904c200bf93.PNG)

**Comment by yukie-a** [comment]
Sorry, it was due to the time-out.

**Comment by yukie-a** [comment]
I got the same error again.. mayb not the time-out??

![EmptyErrorMsg2](https://user-images.githubusercontent.com/67378697/123298569-87d4df00-d510-11eb-83f9-cc257d2cf56e.PNG)

**Comment by senaarpinar** [comment]
Not sure why the error message is empty but I fixed the issue that generated the error. You can test it again tomorrow and let us know if the linker is added correctly.
