### ISSUE TITLE
[FEATURE]Can we make the window bigger / Glycan search function

### ISSUE THREAD

**Issue by yukie-a** [glygener/glygen-array-frontend#16]
<Glycan selection at the new Feature entry>
When I expand the Name colum to see the glycan names, the 'select' buttons are pushed out from the window.

Can we move the 'select' button to the first column?

And, this is my wish but it will be nice if there is a glycan search function...

![SelectButton_OutOfWindow](https://user-images.githubusercontent.com/67378697/123412251-4d6b5080-d5a9-11eb-8c1c-5be88401e258.PNG)

**Comment by ReneRanzinger** [comment]
ADR-471 , ADR-472
