### ISSUE TITLE
[BUG] Error at the "Generic Feature Info"

### ISSUE THREAD

**Issue by yukie-a** [glygener/glygen-array-frontend#17]
I can not find the space to enter 'description', and I'm not sure what particulary the 'group' is used for??

![Error_at_Generic Feature Info](https://user-images.githubusercontent.com/67378697/123413374-9bcd1f00-d5aa-11eb-8902-ed82697f6162.PNG)

**Comment by ReneRanzinger** [comment]
You need to click the cogwheel to add at least one of these descriptors.

**Comment by ReneRanzinger** [comment]
ADR-473

**Comment by yukie-a** [comment]
I see!
