### ISSUE TITLE
[BUG] Password unhide feature not working

### ISSUE THREAD

**Issue by akulmehta** [glygener/glygen-array-frontend#19]
**Describe the bug**
The password unhide feature for log in does not work.

**Page**
https://glygen.ccrc.uga.edu/ggarray/login

**To Reproduce**
1. Go to 'https://glygen.ccrc.uga.edu/ggarray/login'
2. Click on 'eye' icon in the password input field - nothing happens.

**Expected behavior**
Upon clicking the eye icon, the password should be visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/42812604/123855285-baeee800-d8ed-11eb-9679-4efc2a11d7eb.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Firefox Developer Edition
 - Version: 90.0b12 (64-bit)

**Additional context**

**Comment by ReneRanzinger** [comment]
@Sn3108 we will hide this for now.

**Comment by ReneRanzinger** [comment]
ADR-470

**Comment by ReneRanzinger** [comment]
@akulmehta can you please test again? We tested with Windows 10 and firefox and it seems to work,

**Comment by akulmehta** [comment]
Yes it is working.
