### ISSUE TITLE
Glycans are removed while adding a new feature

### ISSUE THREAD

**Issue by yukie-a** [glygener/glygen-array-frontend#26]
(I'm sorry if this is on purppose while updating the Feature Entry...)

**Describe the bug**
Glycans are not displayed at the new feature entry page (page 3).

**Page**
Page 3 (select glycan) of "Add Feature to Repository"

**To Reproduce**
1. Go to 'Features'
2. Click on 'Add Feature'
3. Click on 'Next'
4. Select a linker (e.g. AOPE)
5. Click on 'Next'

**Expected behavior**
A list of glycans was shown before..

**Comment by ReneRanzinger** [comment]
If you go to your Glycan section. Are they still there? 

On addfeature Page 3: In the beginning there is an empty table with just a "Pick Glycan" button. When you click the button your glycan list is empty?

**Comment by yukie-a** [comment]
Yes, I see the list of glycans which I entered previously.

**Comment by yukie-a** [comment]
Aahhh, I see. 

Sorry. Yes, when i clicked the 'pick-up' button, the list of glycan moieties is shown. 
Yes, I knew this function... i don't know why i missed it.
