### ISSUE TITLE
Feature (glycan probe) metadata

### ISSUE THREAD

**Issue by yukie-a** [glygener/glygen-array-frontend#28]
I could not find an excel file for the feature (glycan probe metadata). 
There is also no detailed information in the [Google spread sheet - MIRAGE vs Repsoitory metadata (complete)](https://docs.google.com/spreadsheets/d/1SdVLUxb45mC3EantKIlixW4YklqoT1XJllrVKJyY13E/edit?usp=sharing) .

I am sorry but I don't remember when we discussed these metadata... Could you please tell me?

![NewFeature_metadata](https://user-images.githubusercontent.com/67378697/124743579-c78ac600-df15-11eb-8b44-c681d5c892bd.png)

**Comment by ReneRanzinger** [comment]
We made an online sheet for this since this came up late.
https://docs.google.com/spreadsheets/d/19TOLF8lakS_ruwPB0TfhTvCST9pspHPMmS5uISzREBk/edit#gid=900981853

**Comment by yukie-a** [comment]
Thank you very much for re-sending me the google spreadsheet.
