### ISSUE TITLE
[BUG] Change "Sequence Type" from IUPAC to "Modified IUPAC Condensed"

### ISSUE THREAD

**Issue by akulmehta** [glygener/glygen-array-frontend#29]
**Describe the bug**
To avoid confusion between "IUPAC" please change the `<select>` `<option>` it to "Modified IUPAC Condensed" or `CFG IUPAC Condensed` for the `Sequence Type` field.

**Page**
https://glygen.ccrc.uga.edu/ggarray/glycans/addglycan

**To Reproduce**
1. Go to the page above.

**Expected behavior**
Expect field label change

**Screenshots**
![image](https://user-images.githubusercontent.com/42812604/124771511-2eee4900-df09-11eb-909d-19be68a00021.png)

**Desktop (please complete the following information):**
Not Applicable

**Additional context**

**Comment by ReneRanzinger** [comment]
ADR-478

**Comment by ReneRanzinger** [comment]
Its name "CFG IUPAC Condensed" for now.
