### ISSUE TITLE
Asking for slide Batch ID may be more appropriate under the Slides heading[BUG]

### ISSUE THREAD

**Issue by akulmehta** [glygener/glygen-array-frontend#3]
**Describe the bug**
I think the batch meta data should be asked when you Create Slide (https://glygen.ccrc.uga.edu/ggarray/slides/addSlide) rather than (https://glygen.ccrc.uga.edu/ggarray/listslidemeta/addSlideMeta)

**Page**
https://glygen.ccrc.uga.edu/ggarray/listslidemeta/addSlideMeta (currently located here)
https://glygen.ccrc.uga.edu/ggarray/slides/addSlide (desired)

**To Reproduce**
1. Visit above pages

**Expected behavior**
To move asking the Batch when you select the slide meta data as the batch would change from one slide to another.

**Comment by ReneRanzinger** [comment]
Are you talking about batch ID or what do you mean by batch metadata?

**Comment by akulmehta** [comment]
For the slide the interface was asking us to enter the batch of slides used. Now the options are not visible was anything updated since I posted this?

**Comment by ReneRanzinger** [comment]
Something might have changed but not due to this ticket. I did not create a ticket in JIRA for this since I was not sure about the meaning.

**Comment by ReneRanzinger** [comment]
Is this still an issue or can we close this ticket?

**Comment by akulmehta** [comment]
I think we should close it for now. Will reopen if I see anything.
