### ISSUE TITLE
Empty Error Message in new glycan entry page 

### ISSUE THREAD

**Issue by yukie-a** [glygener/glygen-array-frontend#30]
**Describe the bug**
An empty error message is shown in the new glycan entry page (Page 3 - Review and Add), and I can not finish the entry process.

**Page**
Glycan entry page - Page 3 Review and Add

**To Reproduce**
1. Log in with 'imperialdata' account - for imcomplete microarray data for ICL
2. Go to 'Glycan'
2. Click on 'next'
3. Fill the information (name, glytoucan id etc)
4. Click on 'next'
5. Click on 'finish' 

**Screenshots**
![EmptyError_Glycan_ICLdata](https://user-images.githubusercontent.com/67378697/124783999-6b3b9c80-df3d-11eb-8328-cad779ca6fcc.PNG)

**Comment by ReneRanzinger** [comment]
ADR-479
