### ISSUE TITLE
Add Data Processing page going larger than container[BUG]

### ISSUE THREAD

**Issue by akulmehta** [glygener/glygen-array-frontend#4]
**Describe the bug**
The page is going beyond the container, causing the text to be cut.

**Page**
https://glygen.ccrc.uga.edu/ggarray/dataprocessing/addDataProcessing

**To Reproduce**
1. Go to the page in Firefox.

**Expected behavior**
Expect the form to be centered within its container and probably needs to go into a div.

**Screenshots**

![image](https://user-images.githubusercontent.com/42812604/120554850-41380d00-c3c8-11eb-9bd3-06911ec9581c.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox Developer Edition
 - Version 89.0b15 (64-bit)

**Comment by ReneRanzinger** [comment]
ADR-425

**Comment by Sn3108** [comment]
Fixed the responsive issue of this page and similar pages
