### ISSUE TITLE
Some add button (plus icon) does not work

### ISSUE THREAD

**Issue by yukie-a** [glygener/glygen-array-frontend#44]
**Describe the bug**
Plus icon (e.g. edit sample as well as Assay new entry page) will be disappeared when I clicked.

**Page**
Which webpage did the error occur. 

**To Reproduce**
1. Go to 'Assay'
2. Click on 'Next' after entering the name and selecgt all the assay type
3. Click a plus icon on each assay type -> the icon disappear

**Comment by senaarpinar** [comment]
@yukie-a This is the expected behavior. Once you click +, the new entry is created (either immediately below the item you clicked add, or, for Assay, after all items on the page) and the + icon is now shown in the newly created entry.
