### ISSUE TITLE
Not able to complete the multiple slide layout entry using xml

### ISSUE THREAD

**Issue by yukie-a** [glygener/glygen-array-frontend#45]
**Describe the bug**
I tried to enter the slide layout using XML file. However, a blank page is displayed after uploading a xml file. 

**Page**
Slide Layout Entry 

**To Reproduce**
1. Go to 'Slide Layout'
2. Click on 'Add Multiple Slide Layouts'
3. Upload a test slide layout xml file (copied in my Google Drive - please find from the link below)
     https://drive.google.com/file/d/1E8_88BJ_f0W1ugxKMzt2IxBL4lBKh9C8/view?usp=sharing
4. Click on 'Submit'
5. Select the slide layout uploaded and click 'Add Slide Layout'

**Expected behavior**
If there is an error in my test xml file, could you please display the error... (maybe the line number?) ?

**Comment by senaarpinar** [comment]
There is an error in the slide layout but due to another ticket we are working on (https://ccrcbioinf.atlassian.net/browse/ADR-734), the frontend is not displaying the error. @sujeetvkulkarni will look into this.

@yukie-a It looks like the error is due to the "Empty" feature you put on the slide. This is a feature with a glycan named "Empty" and no linker. By default, we are trying to create a "linked glycan" feature for these entries and it fails since there is no linker. @ReneRanzinger How should we handle these entries? I believe we should not be creating a "Empty" glycan. In my opinion, we should just skip these empty spots and not create any features. If this is the case, how should Yukie specify them in the xml file.

**Comment by senaarpinar** [comment]
I tested a fix by hard coding "empty" in the code to skip these spots. But we should not be using any other string for the name of the empty spots. If we agree on this solution, I can commit my changes.

**Comment by senaarpinar** [comment]
in CFG case, we just leave the spots empty as shown below - see spot 3,1:

<blockLayout NumOfColumn="9" NumOfGroups="20" id="336" name="CFG_V3.0-16" NumOfReplicates="6" NumOfRow="16">
            <level_unit level_concentration="100.0" unit="MICROMOL"/>
            <level_unit level_concentration="10.0" unit="MICROMOL"/>
            <spot featureId="6665" group="1" x="1" y="1">
                <concentration level_concentration="10.0" unit="MICROMOL"/>
            </spot>
            <spot featureId="6666" group="2" x="2" y="1">
                <concentration level_concentration="10.0" unit="MICROMOL"/>
            </spot>
            <spot x="3" y="1"/>
            <spot featureId="6665" group="1" x="4" y="1">
                <concentration level_concentration="10.0" unit="MICROMOL"/>
            </spot>
           
@yukie-a Is it possible to modify your code to generate it this way? If it breaks a lot of things, we can go with the fix I described above.

**Comment by yukie-a** [comment]
Hi @senaarpinar,

Thank you for letting me know the issue .
There is no problem to remover the entries which feature names are 'Empty'.  

However, unfortunately, we have a lot of glyan probes (features) without linker information...

Please find the attached file which i generated for testing. I had to change the format into txt as I could not attach a xml file here. Please change the format when you downloaded into xml.

In this example, over 70 features in one block layout do not have linker informaiton. 
I am currently asking Yan and Ten how they would like to handle these glycan probes (features). 
I do believe that they can find the linker information from lab book or something... 


[icl_lib_ExtractGoldStandard_mask.txt](https://github.com/glygener/glygen-array-frontend/files/9626074/icl_lib_ExtractGoldStandard_mask.txt)
