### ISSUE TITLE
Not able to log in

### ISSUE THREAD

**Issue by yukie-a** [glygener/glygen-array-frontend#60]
**Describe the bug**
I am not able to login the glygen glycan microarray repository page.
Nothing happens when I click 'Log in' button after entering Username and Password.

**Page**
https://glygen.ccrc.uga.edu/array/login

**Desktop (please complete the following information):**
 - OS: Mac OS Ventura
 - Browser: tested using both FireFox (Version 116.0.3) and Chrome (Version 115.0.5790.170)

**Comment by ReneRanzinger** [comment]
@senaarpinar can you please check this? I can login. But there is a [different problem](https://github.com/glygener/glygen-array-backend/issues/128).

**Comment by senaarpinar** [comment]
I checked earlier and I can login too. Checking the logs to see if there are any issues

**Comment by senaarpinar** [comment]
some user accounts seem to be deleted, I need to investigate that. but also, there should be an error message displayed in such as case but the code in "array" server has not been updated to the latest. @ReneRanzinger should I update it to the latest? The repository seems to be empty, not sure when we emptied it.

**Comment by ReneRanzinger** [comment]
Should be fine.

**Comment by yukie-a** [comment]
Thank you for checking
@senaarpinar I'm using glycoscienceslab@gmail.com account. 
I think I have also created 'GlycosciencesLab.icl@gmail.com'...

B
Y

**Comment by senaarpinar** [comment]
@yukie-a those accounts are on ggarray server, the url you posted has “array” instead. “Array” is the production server

**Comment by yukie-a** [comment]
@senaarpinar  thank you. I can log-in to the "ggarray"!   

Just for your information...  
When I am logging-in to the "ggarray", I can not click the login button of "array".  
Probably this will not be an issue for general users, but just for your information.

Thank you once again!

**Comment by senaarpinar** [comment]
Yes, we saw that issue as well and @ReneRanzinger created a new ticket
